version: '3.8'

services:
  config-server:
    image: localstack/localstack:3.2.0
    container_name: config-server
    ports:
      - "4566:4566"
    environment:
      - SERVICES=ssm
      - DEBUG=1
      - PERSISTENCE=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=docker
    volumes:
      # - "./localstack-data:/tmp/localstack/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - localstack-network

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "54322:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=notification_management
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/public:/docker-entrypoint-initdb.d/
    networks:
      - localstack-network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    #    environment:
    #      - OLLAMA_MODELS
    #    deploy:
    #      resources:
    #        limits:
    #          memory: 2g
    #          cpus: '0.5'
    networks:
      - localstack-network

  keycloak:
    container_name: keycloak
    image: keycloak/keycloak:25.0.6
    command:
      - start-dev
      - --import-realm
    environment:
      KC_HOSTNAME: localhost
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: secret
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: secret
      KC_HEALTH_ENABLED: "true"
      KC_FEATURES: account-api,account3,authorization,client-policies,impersonation,docker,scripts,admin-fine-grained-authz
    ports:
      - "8081:8080"
      - "9000:9000"
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;" ]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - ./keycloak/import/:/opt/keycloak/data/import/
networks:
  localstack-network:
    driver: bridge
volumes:
  postgres-data: 