global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. Default is every 1 minute.

scrape_configs:
  - job_name: 'notification-management'
    static_configs:
      - targets: ['host.docker.internal:8080'] # Assuming your Go app runs on 8080 and exposes /metrics

# Queries
#  sum(notification_management_requests_total) by (url)