global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'notification-management'
    static_configs:
      - targets: ['app:8080']
    metrics_path: /api/metrics

# Queries
#  sum(notification_management_requests_total) by (url)