apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  serviceName: "config-server"
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: localstack/localstack:3.2.0
          ports:
            - containerPort: 4566
          env:
            - name: SERVICES
              value: "ssm,config"
            - name: DEBUG
              value: "1"
            - name: PERSISTENCE
              value: "1"
            - name: DATA_DIR
              value: "/tmp/localstack/data"
            - name: LAMBDA_EXECUTOR
              value: "docker"
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
            - name: config-data
              mountPath: /var/lib/localstack
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
  volumeClaimTemplates:
    - metadata:
        name: config-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  selector:
    app: config-server
  ports:
    - protocol: TCP
      port: 4566
      targetPort: 4566
  type: ClusterIP
