apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: keycloak/keycloak:25.0.6
          command:
            - /opt/keycloak/bin/kc.sh
            - start-dev
            - --import-realm
          env:
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nms-secrets
                  key: KEYCLOAK_PASSWORD
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nms-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD
          envFrom:
            - configMapRef:
                name: nms-config
          ports:
            - containerPort: 8080
            - containerPort: 9000
          volumeMounts:
            - name: keycloak-import
              mountPath: /opt/keycloak/data/import/
      volumes:
        - name: keycloak-import
          configMap:
            name: keycloak-import
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
      name: http
    - protocol: TCP
      port: 9000
      targetPort: 9000
      name: management
  type: ClusterIP
